service: Serverless-Boilerplate
frameworkVersion: "3"
plugins:
    - serverless-esbuild
    - serverless-plugin-git-variables
    - serverless-prune-plugin
    - serverless-lift
    - serverless-plugin-lambda-insights

provider:
    name: aws
    runtime: nodejs14.x
    region: eu-central-1
    stage: ${opt:stage,"dev"}
    tracing:
        lambda: true

custom:
    lambdaInsights:
        defaultLambdaInsights: true
    esbuild:
        bundle: true
        minify: false
        sourcemap: external
        exclude:
            - "aws-sdk"
    prune:
        automatic: true
        number: 3
    manifest:
        output: ./serverless.manifest.json
        disableOutput: false
        silent: false
        srcPath: ./serverless.yml

functions:
    health:
        handler: "src/index.health"
        tracing: Active
        events:
            - http:
                  path: "/health"
                  method: get
                  cors: true

constructs:
    boilerplate-bucket:
        type: storage

    boilerplate-table:
        type: database/dynamodb-single-table
